services:
    openvpn:
       container_name: openvpn
       # If you want to build your own image with docker-compose, uncomment the next line, comment the "image:" line and run "docker-compose build" following by "docker-compose up -d"
       # build: .
       image: iamjanam/openvpn-server-with-ui:latest
       ports: 
          - "1194:1194/udp"
         # - "2080:2080/tcp"  # management port. uncomment if you would like to share it with the host
       privileged: true
       env_file: 
          - ./compose.env
       environment:
           TRUST_SUB: ${TRUST_SUB}
           GUEST_SUB: ${GUEST_SUB}
           HOME_SUB: ${HOME_SUB}
       volumes:
           - ./pki:/etc/openvpn/pki
           - ./clients:/etc/openvpn/clients
           - ./config:/etc/openvpn/config
           - ./staticclients:/etc/openvpn/staticclients
           - ./log:/var/log/openvpn
           - ./fw-rules.sh:/opt/app/fw-rules.sh
           - ./checkpsw.sh:/opt/app/checkpsw.sh
       cap_add:
           - NET_ADMIN
       restart: always
       depends_on:
           - "openvpn-ui"

    openvpn-ui:
       container_name: openvpn-ui
       image: d3vilh/openvpn-ui:latest
       env_file: 
           - ./compose.env
       environment:
           - OPENVPN_ADMIN_USERNAME=${OPENVPN_ADMIN_USERNAME}
           - OPENVPN_ADMIN_PASSWORD=${OPENVPN_ADMIN_PASSWORD}
       ports:
           - "8080:8080/tcp"
       volumes:
           - ./:/etc/openvpn
           - ./db:/opt/openvpn-ui/db
           - ./pki:/usr/share/easy-rsa/pki
           - /var/run/docker.sock:/var/run/docker.sock:ro
       restart: always
